config/routes.rb
Rails.application.routes.draw do
  #devise_for :homes

  devise_for :users
  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'sign_up/:id' => 'devise/registrations#new'
  
  #get 'sign_in/:id' => 'devise/sessions#new'

  resources :users,only: [:show,:index,:edit,:update] do
     member do
     get :following
     get :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
      resource :favorites, only: [:create, :destroy]
      resources :book_comments, only: [:create, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	#has_many :user

	belongs_to :user
	has_many :favorites, dependent: :destroy
	has_many :book_comments, dependent: :destroy

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
	belongs_to :user
	belongs_to :book

	validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user
	belongs_to :book
end

app/models/home.rb
class Home < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/relationship.rb
class Relationship < ApplicationRecord
	# 存在しないクラス参照を防ぐ
	belongs_to :follower, class_name: 'User'
	belongs_to :following, class_name: "User"

	validates :follower_id, presence: :true
	validates :following_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  ### フォロー機能アソシエーション ###
  # フォロー出来るユーザーを取得
  has_many :following_relationships, foreign_key: "follower_id", class_name: "Relationship", dependent: :destroy
  # フォローしてるユーザーを取得
  has_many :followings, through: :following_relationships
  # フォローされているユーザーを取得
  has_many :follower_relationships, foreign_key: "following_id", class_name: "Relationship", dependent: :destroy
  has_many :followers, through: :follower_relationships

  # フォローしているか調べる関数
  def following?(other_user)
    following_relationships.find_by(following_id: other_user.id)
  end

  # フォローする関数
  def follow!(other_user)
    following_relationships.create!(following_id: other_user.id)
  end

  # フォローを外す関数
  def unfollow!(other_user)
    following_relationships.find_by(following_id: other_user.id).destroy
  end

  attachment :profile_image, destroy: false

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: {maximum:50}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :configure_permitted_parameters, if: :devise_controller?
	#デバイス機能実行前にconfigure_permitted_parametersの実行をする。
	protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email])
    #sign_upの際にnameのデータ操作を許。追加したカラム。

    devise_parameter_sanitizer.permit(:sign_in,keys:[:name])
  end


  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end

  #sign_out後のredirect先変更する。rootパスへ。rootパスはhome topを設定済み。
  def after_sign_out_path_for(resource)
    root_path
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
	def create
		book = Book.find(params[:book_id])
    	comment = current_user.book_comments.new(book_comment_params)
    	comment.book_id = book.id
    	comment.save
    	redirect_to book_path(book)
	end

	def destroy
		book = Book.find(params[:book_id])
		book_comment = BookComment.find(params[:id])
		book_comment.destroy
		redirect_to book_path(book)
	end

	private
	def book_comment_params
		params.require(:book_comment).permit(:comment)
	end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!

  before_action :fraud_prevntion, only: [:edit, :update]

  # 不正アクセス防止
  def fraud_prevntion
    @book = Book.find(params[:id])
    unless current_user.id == @book.user.id
      redirect_to books_path
    end
  end



  def show
  	@book = Book.find(params[:id])
    @nil = Book.new #本の投稿がないとき
    @book_comment = BookComment.new
  end

  def index
    @nil = Book.new
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
    @books = Book.all
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to  book_path(@book.id), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		redirect_to  books_path(@book.id), notice: "error !!!"
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	book = Book.find(params[:id])
  	if book.update(book_params)
  		redirect_to book_path(book.id), notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		#render "edit"
      redirect_to  book_path(book.id), notice: "error !!!"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
	def create
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.new(book_id: book.id)
        favorite.save
        if book == current_user
        redirect_to books_path(@book.id)
       	else
        redirect_to books_path(book.id)
        end
    end
    def destroy
        book = Book.find(params[:book_id])
        favorite = current_user.favorites.find_by(book_id: book.id)
        favorite.destroy
        if book == current_user
        redirect_to books_path(@book.id)
       	else
        redirect_to books_path(book.id)
        end
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController


  def create
    @user = User.find(params[:relationship][:following_id])
    current_user.follow!(@user)
    redirect_to @user
  end

  def destroy
    @user = Relationship.find(params[:id]).following
    current_user.unfollow!(@user)
    redirect_to @user
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
	before_action :baria_user, only: [:edit,:update]

  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'following'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'followers'
  end


  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	user = User.find(params[:id])
  	if user.update(user_params)
  		redirect_to user_path(current_user.id), notice: "successfully updated user!"
  	else
  		redirect_to user_path(current_user.id)
      flash[:notice] = "error !!!"
  	end
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_newform.html.erb
<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">

<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ 右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @nil %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to user_path(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>
				

					<% if book.favorited_by?(current_user) %>
  					<td>
    					<%= link_to book_favorites_path(book), method: :delete do %>
      					<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
      					<%= book.favorites.count %>
    					<% end %>
  					</td>
					<% else %>
  					<td>
    					<%= link_to "/books/#{book.id}/favorites", method: :post do %>
      					<i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>

      					<%= book.favorites.count %>
    					<% end %>
  					</td>
					<% end %>


					<td>
					<i class="fa fa-comment"></i>
					<a href="#comments">コメント数：<%= book.book_comments.count %></a>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>

		<!--books一覧 -->


	</div>
</div>

app/views/books/show.html.erb
<div class="row">
<div class="col-xs-3">

	<h2>User info</h2>
	<%= render 'users/profile', user: @book.user%>

	<h2>New book</h2>
	<%= form_for(@nil, url: '/books', method: :post) do |f| %>
		<div class="field row">
			<%= f.label :title %>
			<%= f.text_field :title, class: "col-xs-12 book_title" %>
		</div>

		<div class="field row">
			<%= f.label :body %> <!-- ここを変更 -->
			<%= f.text_area :body, class: "col-xs-12 book_body" %>
		</div>

		<div class="actions row">
			<%= f.submit class: "btn btn-primary col-xs-12" %>
		</div>
<% end %>

</div>

<div class="col-xs-9">
	<h2>Book detail</h2>

	<table class="table">
			<tr>
				<td>
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td><%= link_to @book.title, @book %></td>
				<td><%= @book.body %></td>

				<!-- いいね機能追加 -->
				<% if @book.favorited_by?(current_user) %>
  					<td>
    					<%= link_to book_favorites_path(@book), method: :delete do %>
      					<i class="glyphicon glyphicon-heart" aria-hidden="true" style="color: red;"></i>
      					<%= @book.favorites.count %>
    					<% end %>
  					</td>
					<% else %>
  					<td>
    					<%= link_to "/books/#{@book.id}/favorites", method: :post do %>
      					<i class="glyphicon glyphicon-heart-empty" aria-hidden="true"></i>

      					<%= @book.favorites.count %>
    					<% end %>
  					</td>
				<% end %>

				<!-- コメント件数表示 -->
				<td>
					<i class="fa fa-comment"></i>
					<a href="#comments">コメント数：<%= @book.book_comments.count %></a>
				</td>

				<% if @book.user == current_user %>
				<!-- 編集 -->
				<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
				<!-- 削除 -->
				<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %>
				</td>
				<% end %>
			</tr>
		</table>

			<% if @book.user == current_user %>
				<!-- コメント入力フォーム -->
				<%= form_for [@book,@book_comment] do |f| %>
					<%= f.text_area :comment, class: "col-xs-12 comment" %>
					<%= f.submit "送信" %>
				<% end %>
			<% end %>

			<br>

			<!-- コメント表示 -->
			<h4>コメント一覧</h4>
			<ol>
    			<% @book.book_comments.each do |book_comment| %>
        			<li class="comment">
                    	<div class="comment-entry"><%= book_comment.comment %>


                    	</div>
                    		<!-- 削除 -->
						<%= link_to "削除","/books/#{@book.id}/book_comments/#{book_comment.id}", method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "destroy_book_#{@book_comment.id}" %>
        			</li>
    			<% end %>
			</ol>

</div>
</div>

app/views/home/top.html.erb
<div class="row">
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_sessions_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registrations_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>

	</div>
</div>

app/views/homes/about.html.erb
<h1>welcome to<span class="glyphicon glyphicon-book"></span>
<strong>Bookers</strong>  !!</h1>

app/views/homes/top.html.erb
<div class="continer">
<div class="row">
<body>
	<div class="main col-md-offset-3 col-md-6">
		<h1>welcome to<span class="glyphicon glyphicon-book"></span>
			<strong>Bookers</strong>  !!</h1>
			<p>In <span class="glyphicon glyphicon-book"></span><strong>Bookers</strong>,</p>
			<p>you can share and exchange your opinions , inpressions , and emotions</p>
			<p>about varioius books!</p>

			<div class="btn-wrapper">
				<div class="row">
					<p><%=link_to "Log in", new_user_session_path, class: "btn btn-info col-xs-10 col-xs-offset-1" %></p>
				</div>
				<div class="row">
					<p><%=link_to "Sign up", new_user_registration_path, class: "btn btn-success col-xs-10 col-xs-offset-1" %></p>
				</div>
			</div>
	</div>
</body>
</div>
</div>

app/views/relationships/index.html.erb
<!-- <<フォロー 一覧>> -->
<h2>Follow Users</h2>
<!--follower一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= attachment_image_tag(user.followings, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.followings.name%></td>

			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>
			<td><%= link_to "フォローを外す", "relationships_path(current_user.id)" %></td>
			</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
	</tbody>
</table>
<!--follower一覧 -->

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
			<th>follows</th>
			<th>
			<%= link_to following_user_path(current_user.id) do %>
				<%= user.followings.count %>
			<% end %>
			</th>
		</tr>

		<tr>
			<th>followers</th>
			<th>
			<%= link_to followers_user_path(current_user.id) do %>
				<%= user.followers.count %></th>
			<% end %>
		</tr>

</table>

<!-- フォローボタン追加 -->
<!-- ログインユーザーじゃない時 -->
<div class="row">
	<% if current_user == user %>
		<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>

  	<% elsif current_user.following?(@user) %>
    	<%= form_for(current_user.following_relationships.find_by(following_id: @user), html: { method: :delete }) do |f| %>
      	<%= f.submit 'フォローを外す', class: 'col-xs-6 btn btn-primary' %>
    	<% end %>

  	<% else %>
    	<%= form_for(current_user.following_relationships.build(following_id: @user.id)) do |f| %>
      	<div><%= f.hidden_field :following_id %></div>
      	<%= f.submit 'フォローする', class: 'col-xs-6 btn btn-success' %>
    	<% end %>

    <% end %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/follower_users.html.erb
<!-- <<フォロワー 一覧>> -->
<h2>Follower Users</h2>
<!--follower一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>

			<td>フォロー数：<%= user.followers.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>

			</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--follower一覧 -->

app/views/users/followers.html.erb
<!-- <<フォロワー 一覧>> -->
<h2>Follower Users</h2>
<!--follower一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>

			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>

			<td>
			<% if current_user.following?(user) %>
				<%= link_to "フォローを外す", relationship_path(user.id) %>
			<% elsif current_user != user %>
				<%= link_to "フォローする", relationships_path %>
			<% end %>
			</td>


			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--follower一覧 -->

app/views/users/following.html.erb
<!-- <<フォロー 一覧>> -->
<h2>Follower Users</h2>
<!--follower一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>

			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>

			<td>
			<% if current_user.following?(user) %>
				<%= link_to "フォローを外す", relationship_path(user.id) %>
			<% elsif current_user != user %>
				<%= link_to "フォローする", relationships_path %>
			<% end %>
			</td>

			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--follower一覧 -->

app/views/users/index.html.erb
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: current_user %>
<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>

</div>

<div class="col-xs-9">
<h2>Users</h2>
<!--users一覧 -->
<table class="table">
	<thead>
		<tr>
			<th>image</th>
			<th>name</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @users.each do |user| %>
		<tr>
			<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
			<td><%= user.name%></td>

			<td>フォロー数：<%= user.followings.count %></td>
			<td>フォロワー数：<%= user.followers.count %></td>
			<td>
			<% if current_user.following?(user) %>
				<%= link_to "フォローを外す", relationship_path(user.id) %>
			<% elsif current_user != user %>
				<%= link_to "フォローする", relationships_path %>
			<% end %>
			</td>
			<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--users一覧 -->

</div>
</div>

app/views/users/show.html.erb
<div class="row">
<div class="col-xs-3">
<h2>User info</h2>
<%= render 'users/profile', user: @user %>
<!--同コントローラーのviewで表示ならusersは省略可 -->

<h2>New book</h2>
<%= render 'books/newform', book: @book %>


</div>

<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to user_path(book.user) do %>
				<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
		</tr>
		<% end %>
	</tbody>
</table>
<!--books一覧 -->

</div>
</div>